name: Daily Temp Forecast Update

on:
  schedule:
    - cron: '0 4 * * *'  # Runs at 4 am everyday UTC
  workflow_dispatch:  # Allows manual triggers

jobs:
  update_forecast:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Update last_update.txt
      run: |
        echo $(date -u) > last_update.txt
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "trinity.ljq@gmail.com"
        git config --local user.name "tweeneetee"
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update forecast data and last update time" && git push)
